services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="bertrandmartel/gitlab-backup"
    - docker build -t "$image" .
    - docker inspect "$image"

script:
    - official-images/test/run.sh "$image"

after_script:
    - docker images
